# Generated by Django 3.0.5 on 2020-04-09 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in_out', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_in_out',
            name='loan_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 14, 42, 24, 193027)),
        ),
    ]
