# Generated by Django 3.0.5 on 2020-04-15 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in_out', '0006_auto_20200415_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_in_out',
            name='loan_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 11, 19, 16, 85572)),
        ),
    ]
