# Generated by Django 3.0.5 on 2020-04-16 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in_out', '0009_auto_20200416_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check_in_out',
            old_name='loan_return_datetime',
            new_name='checked_in_datetime',
        ),
        migrations.RemoveField(
            model_name='check_in_out',
            name='loan_datetime',
        ),
        migrations.AddField(
            model_name='check_in_out',
            name='checked_out_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 19, 50, 34, 658415)),
        ),
    ]
