# Generated by Django 3.0.5 on 2020-04-09 14:27

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=43)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
